### ISSUE TITLE
Code Review Issue

### ISSUE THREAD

**Issue by huangs1** [lussierc/refinedNotepadPython#3]
### Date of the review: 11/08/18
Inspection rate: 10 lines per min. About 9 mins total.
Defect Rate: I didn't find any bugs in the code.
Defect density: 0 bugs per line

### Checklist
- [ ] Code Formatting
There isn't a specific style that your code is following.
- [x] Coding Best Practices
There are a lot of good comments that explain what each line of code does. This would definitely help those that want to understand the code but are new to the language.
- [x] Code Readability
The code is well organized but does need to be formatted toward a specific style guide to make it more generically readable for other professionals. 
- [x] Code Testability
The functions are well organized and separated where there are no overlapping or confusion on which part of the code is for which function to the program.
- [x] Code Reliability
- [x] Usability

**Comment by lussierc** [comment]
@huangs1 Thanks for the code review! I will look into your comments and update my code formatting soon!

**Comment by lussierc** [comment]
@huangs1 I have better formatted the code and it is now following the PEP8 style guide based on your comments and review.

**Comment by lussierc** [comment]
Updating the checklist after updates so everything is fixed and checked on the list. The code now adheres to the PEP8 style guide. As a result, I am closing this issue.

### Checklist
- [x] Code Formatting
There isn't a specific style that your code is following.
- [x] Coding Best Practices
There are a lot of good comments that explain what each line of code does. This would definitely help those that want to understand the code but are new to the language.
- [x] Code Readability
The code is well organized but does need to be formatted toward a specific style guide to make it more generically readable for other professionals. 
- [x] Code Testability
The functions are well organized and separated where there are no overlapping or confusion on which part of the code is for which function to the program.
- [x] Code Reliability
- [x] Usability
